### ISSUE TITLE
Add Travis tests for ensuring that rfc2mnadoc.sh works

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/rfc2mn#1]
```sh
./rfc2mnadoc.sh test.xml text.adoc
```

And compare `text.adoc` to the proper text.

**Comment by CAMOBAP** [comment]
@ronaldtse which `*.xml` can I use as test input?

**Comment by ronaldtse** [comment]
@CAMOBAP795 can you use these?

* https://tools.ietf.org/id/draft-ribose-asciirfc-08.xml
* https://tools.ietf.org/id/draft-asciirfc-minimal-03.xml

**Comment by CAMOBAP** [comment]
@ronaldtse should this script support OSX? should we populate `external` directory with more data based on https://travis-ci.com/metanorma/rfc2mn/jobs/217214172 ?

**Comment by ronaldtse** [comment]
Yes, we should fix it for macOS. Thanks.
